global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'django-backend'
    static_configs:
      - targets: ['backend:8000'] 
        labels:
          group: 'django-backend'
    metrics_path: '/api/metrics/prometheus' 

