name: Backend Tests

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DEBUG: True
      RUN_MODE: test
      DATABASE_URL: backend/db.sqlite3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Migrations
      working-directory: backend
      run: |
        python3 manage.py makemigrations
        python3 manage.py migrate

    - name: Running tests
      working-directory: backend
      run: |
        pytest

